-- Migration 019: workout_sessions — logged workouts of the workout module.
--
-- Applied in numeric order on boot. The MigrationRunner wraps this file in ONE
-- transaction under an advisory lock — do NOT add BEGIN/COMMIT. Idempotent DDL.
--
-- A session is one workout: its exercises in order and their sets. The
-- health_* and band_* columns hold what the workout_reconcile job attached
-- from the Mi Fitness tables; they are derived data and can be recomputed.

CREATE TABLE IF NOT EXISTS workout_sessions (
    id                 uuid             PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id           uuid             NOT NULL,
    routine_id         uuid             REFERENCES routines (id) ON DELETE SET NULL,
    name               text             NOT NULL DEFAULT '',
    started_at         timestamptz      NOT NULL DEFAULT now(),
    finished_at        timestamptz,
    note               text             NOT NULL DEFAULT '',
    -- Latest body weight known when the session started (body_measurements).
    bodyweight_kg      double precision,
    -- NULL until the session is finished; then pending | matched | no_data.
    health_status      text             CHECK (health_status IN ('pending', 'matched', 'no_data')),
    hr_avg             integer,
    hr_max             integer,
    hr_samples         integer          NOT NULL DEFAULT 0,
    band_workout_id    text,
    band_calories_kcal double precision,
    reconciled_at      timestamptz,
    created_at         timestamptz      NOT NULL DEFAULT now(),
    updated_at         timestamptz      NOT NULL DEFAULT now(),
    CHECK (finished_at IS NULL OR finished_at >= started_at)
);
-- One unfinished session per owner.
CREATE UNIQUE INDEX IF NOT EXISTS one_active_workout_session ON workout_sessions (owner_id) WHERE finished_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_workout_sessions_owner_started ON workout_sessions (owner_id, started_at DESC);
-- The reconcile job scans finished sessions by time.
CREATE INDEX IF NOT EXISTS idx_workout_sessions_finished ON workout_sessions (finished_at) WHERE finished_at IS NOT NULL;

DROP TRIGGER IF EXISTS workout_sessions_touch_updated_at ON workout_sessions;
CREATE TRIGGER workout_sessions_touch_updated_at
    BEFORE UPDATE ON workout_sessions
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE IF NOT EXISTS session_exercises (
    id                      uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id              uuid    NOT NULL REFERENCES workout_sessions (id) ON DELETE CASCADE,
    exercise_id             text    NOT NULL REFERENCES exercises (id) ON DELETE RESTRICT,
    position                integer NOT NULL,
    -- Targets copied from the routine when the session started.
    target_sets             integer,
    target_reps_min         integer,
    target_reps_max         integer,
    target_duration_seconds integer,
    rest_seconds            integer NOT NULL DEFAULT 90,
    note                    text    NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_session_exercises_session ON session_exercises (session_id, position);
CREATE INDEX IF NOT EXISTS idx_session_exercises_exercise ON session_exercises (exercise_id);

CREATE TABLE IF NOT EXISTS workout_sets (
    -- Generated by the client, so a resent set replaces itself.
    id                  uuid             PRIMARY KEY,
    session_exercise_id uuid             NOT NULL REFERENCES session_exercises (id) ON DELETE CASCADE,
    position            integer          NOT NULL,
    kind                text             NOT NULL DEFAULT 'work' CHECK (kind IN ('work', 'warmup')),
    weight_kg           double precision CHECK (weight_kg BETWEEN 0 AND 2000),
    reps                integer          CHECK (reps BETWEEN 0 AND 10000),
    duration_seconds    integer          CHECK (duration_seconds BETWEEN 0 AND 86400),
    distance_m          double precision CHECK (distance_m BETWEEN 0 AND 1000000),
    rpe                 numeric(3, 1)    CHECK (rpe BETWEEN 1 AND 10),
    completed_at        timestamptz      NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_workout_sets_session_exercise ON workout_sets (session_exercise_id, position);
