apiVersion: v1
kind: Service
metadata:
  name: {{ include "life-os-cpp.fullname" . }}
  labels:
    {{- include "life-os-cpp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "life-os-cpp.selectorLabels" . | nindent 4 }}
