/**
 * @file Endpoints.hpp
 * @brief Endpoint registry — the single source of truth for routes.
 * @details `docs/openapi.yaml` is checked against this list in CI via
 *          scripts/check-openapi-drift.sh; `--print-routes` prints it.
 *          Add a line here for every new ADD_METHOD_TO.
 */

#pragma once

#include <string>
#include <vector>

namespace Api {

/**
 * @brief Endpoint metadata: method, path, description
 */
struct EndpointInfo {
    std::string method;
    std::string path;
    std::string description;
};

/**
 * @brief Single source of truth for all registered API endpoints
 */
inline const std::vector<EndpointInfo>& get_endpoints() {
    static const std::vector<EndpointInfo> endpoints = {
        {"GET", "/", "Endpoint discovery"},
        {"GET", "/healthz", "Liveness probe"},
        {"GET", "/ready", "Readiness probe"},
        {"GET", "/health", "Detailed health check"},
        {"POST", "/api/v1/auth/register", "Register a new user"},
        {"POST", "/api/v1/auth/login", "Log in (issues access + refresh cookies)"},
        {"POST", "/api/v1/auth/logout", "Log out (clears cookies + revokes refresh)"},
        {"POST", "/api/v1/auth/refresh", "Rotate access + refresh cookies"},
        {"GET", "/api/v1/auth/me", "Get the authenticated user"},
        {"POST", "/api/v1/account/confirm-resend", "Resend email confirmation link"},
        {"POST", "/api/v1/account/confirm/{token}", "Confirm an account from token"},
        {"POST", "/api/v1/account/reset-password-request", "Request a password-reset email"},
        {"POST", "/api/v1/account/reset-password/{token}", "Reset password using a token"},
        {"POST", "/api/v1/account/change-email-request", "Request a confirm-email link for a new address"},
        {"POST", "/api/v1/account/change-email/{token}", "Apply a pending email change from token"},
        {"POST", "/api/v1/account/join-from-invite/{token}", "Set password and confirm account from an invite token"},
        {"POST", "/api/v1/account/change-password", "Change password while logged in"},
        {"GET", "/api/v1/account/api-keys", "List your API keys"},
        {"POST", "/api/v1/account/api-keys", "Create an API key (secret shown once)"},
        {"DELETE", "/api/v1/account/api-keys/{id}", "Revoke an API key"},
        {"GET", "/api/v1/admin/users", "Admin: list users"},
        {"POST", "/api/v1/admin/users", "Admin: create a user"},
        {"POST", "/api/v1/admin/invite", "Admin: invite a user via email"},
        {"GET", "/api/v1/admin/users/{id}", "Admin: user detail"},
        {"PATCH", "/api/v1/admin/users/{id}", "Admin: update user (email, role, name)"},
        {"DELETE", "/api/v1/admin/users/{id}", "Admin: delete user"},
        {"GET", "/api/v1/admin/roles", "Admin: list roles"},
        {"POST", "/api/v1/admin/roles", "Admin: create role"},
        {"PATCH", "/api/v1/admin/roles/{id}", "Admin: update role (name, permissions, is_default)"},
        {"DELETE", "/api/v1/admin/roles/{id}", "Admin: delete role"},
        {"GET", "/api/v1/admin/audit", "Admin: list the audit trail (requires audit-read permission)"},
        {"GET", "/api/v1/jobs", "List jobs"},
        {"POST", "/api/v1/jobs", "Submit job"},
        {"GET", "/api/v1/jobs/dlq", "List dead-letter queue"},
        {"POST", "/api/v1/jobs/dlq/{id}/requeue", "Requeue a DLQ job"},
        {"GET", "/api/v1/jobs/{id}", "Get job status"},
        {"DELETE", "/api/v1/jobs/{id}", "Cancel job"},
        {"GET", "/api/v1/fitness/account", "Fitness: link status of your Mi account"},
        {"PATCH", "/api/v1/fitness/account", "Fitness: set the cloud region of your Mi account"},
        {"DELETE", "/api/v1/fitness/account", "Fitness: unlink your Mi account, optionally with its data"},
        {"POST", "/api/v1/fitness/account/link", "Fitness: start linking a Mi account by QR sign-in"},
        {"GET", "/api/v1/fitness/account/link/{link_id}", "Fitness: one step of waiting for the QR confirmation"},
        {"POST", "/api/v1/fitness/account/detect-region", "Fitness: find the cloud region that holds your data"},
        {"GET", "/api/v1/fitness/probe", "Fitness: live check of the Xiaomi credentials and cloud"},
        {"POST", "/api/v1/fitness/sync", "Fitness: enqueue a cloud sync run"},
        {"GET", "/api/v1/fitness/sync/{id}", "Fitness: read a sync run's journal entry"},
        {"GET", "/api/v1/fitness/daily-activity", "Fitness: daily activity rows for a date range"},
        {"GET", "/api/v1/fitness/sleep", "Fitness: sleep sessions for a date range"},
        {"GET", "/api/v1/fitness/heart-rate", "Fitness: heart rate samples for a date range"},
        {"GET", "/api/v1/fitness/stress", "Fitness: stress samples for a date range"},
        {"GET", "/api/v1/fitness/spo2", "Fitness: SpO2 samples for a date range"},
        {"GET", "/api/v1/fitness/body", "Fitness: body measurements for a date range"},
        {"GET", "/api/v1/fitness/workouts", "Fitness: workouts for a date range"},
        {"GET", "/api/v1/fitness/summary", "Fitness: per-day summary (steps, sleep, resting heart rate)"},
        {"GET", "/api/v1/fitness/abnormal-heart-beat", "Fitness: abnormal heart beat events for a date range"},
        {"GET", "/api/v1/fitness/coverage", "Fitness: per-type coverage (first/last date, records, last sync)"},
        {"GET", "/api/v1/fitness/export", "Fitness: export rows as a schema_version 1.0 json envelope or csv"},
        {"GET", "/api/v1/workout/exercises", "Workout: search the exercise library and own exercises"},
        {"POST", "/api/v1/workout/exercises", "Workout: create a custom exercise"},
        {"GET", "/api/v1/workout/exercises/{id}", "Workout: read one exercise"},
        {"PATCH", "/api/v1/workout/exercises/{id}", "Workout: edit a custom exercise or a library one's mode"},
        {"GET", "/api/v1/workout/routines", "Workout: list routines"},
        {"GET", "/api/v1/workout/routines/{id}", "Workout: read a routine with its exercises"},
        {"PUT", "/api/v1/workout/routines/{id}", "Workout: create or replace a routine"},
        {"DELETE", "/api/v1/workout/routines/{id}", "Workout: delete a routine"},
        {"POST", "/api/v1/workout/sessions", "Workout: start a session, empty or from a routine"},
        {"GET", "/api/v1/workout/sessions", "Workout: history of finished sessions"},
        {"GET", "/api/v1/workout/sessions/active", "Workout: the unfinished session, or null"},
        {"GET", "/api/v1/workout/sessions/{id}", "Workout: read one session with exercises and sets"},
        {"PATCH", "/api/v1/workout/sessions/{id}", "Workout: finish, rename or move a session"},
        {"DELETE", "/api/v1/workout/sessions/{id}", "Workout: delete a session"},
        {"POST", "/api/v1/workout/sessions/{id}/exercises", "Workout: add an exercise to a session"},
        {"DELETE", "/api/v1/workout/sessions/{id}/exercises/{eid}", "Workout: drop an exercise from a session"},
        {"GET", "/api/v1/workout/sessions/{id}/heart-rate", "Workout: heart-rate samples inside a session"},
        {"PUT", "/api/v1/workout/sets/{id}", "Workout: create or replace a set by its client id"},
        {"DELETE", "/api/v1/workout/sets/{id}", "Workout: delete a set"},
        {"GET", "/api/v1/workout/readiness", "Workout: sleep, resting heart rate and stress before a workout"},
        {"POST", "/api/v1/workout/reconcile", "Workout: re-attach Mi Fitness data to sessions of a date range"},
        {"GET", "/api/v1/food/goals", "Food: goals profile and the computed daily targets"},
        {"PUT", "/api/v1/food/goals", "Food: replace the goals profile"},
        {"GET", "/api/v1/food/items", "Food: search own products"},
        {"POST", "/api/v1/food/items", "Food: create a product"},
        {"POST", "/api/v1/food/items/from-off", "Food: copy an Open Food Facts product by barcode"},
        {"PATCH", "/api/v1/food/items/{id}", "Food: edit a product"},
        {"DELETE", "/api/v1/food/items/{id}", "Food: delete a product, or archive one the diary uses"},
        {"GET", "/api/v1/food/recent", "Food: products used recently"},
        {"GET", "/api/v1/food/off/search", "Food: search Open Food Facts"},
        {"GET", "/api/v1/food/day", "Food: one day of the diary with totals and targets"},
        {"GET", "/api/v1/food/week", "Food: seven days of totals against the targets"},
        {"POST", "/api/v1/food/entries", "Food: add a diary entry"},
        {"POST", "/api/v1/food/entries/batch", "Food: add several diary entries at once"},
        {"PATCH", "/api/v1/food/entries/{id}", "Food: edit a diary entry"},
        {"DELETE", "/api/v1/food/entries/{id}", "Food: delete a diary entry"},
        {"POST", "/api/v1/food/parse", "Food: send a text description to the LLM parse job"},
        {"GET", "/api/v1/food/parse/{id}", "Food: read a parse job and its lines"},
        {"GET", "/api/v1/money/currencies", "Money: the user's currencies"},
        {"POST", "/api/v1/money/currencies", "Money: add or replace a currency"},
        {"PATCH", "/api/v1/money/currencies/{code}", "Money: change a currency"},
        {"GET", "/api/v1/money/accounts", "Money: accounts with their computed balances"},
        {"POST", "/api/v1/money/accounts", "Money: create an account"},
        {"GET", "/api/v1/money/accounts/{id}", "Money: one account"},
        {"PATCH", "/api/v1/money/accounts/{id}", "Money: change an account (not its currency)"},
        {"DELETE", "/api/v1/money/accounts/{id}", "Money: delete an unused account or archive one in use"},
        {"GET", "/api/v1/money/categories", "Money: categories with their budgets"},
        {"POST", "/api/v1/money/categories", "Money: create a category"},
        {"GET", "/api/v1/money/categories/{id}", "Money: one category"},
        {"PATCH", "/api/v1/money/categories/{id}", "Money: change a category or its budget"},
        {"DELETE", "/api/v1/money/categories/{id}", "Money: delete an unused category or archive one in use"},
        {"GET", "/api/v1/money/transactions", "Money: the ledger, filtered and paged"},
        {"POST", "/api/v1/money/transactions", "Money: add an income, expense or adjustment"},
        {"POST", "/api/v1/money/transactions/batch", "Money: add up to 100 rows in one transaction"},
        {"GET", "/api/v1/money/transactions/{id}", "Money: one row with its adjustments"},
        {"PATCH", "/api/v1/money/transactions/{id}", "Money: change a row"},
        {"DELETE", "/api/v1/money/transactions/{id}", "Money: delete a row and its adjustments"},
        {"POST", "/api/v1/money/transactions/{id}/confirm", "Money: post a pending row"},
        {"GET", "/api/v1/money/inbox", "Money: pending rows with the duplicate flag"},
        {"GET", "/api/v1/money/transfers", "Money: transfers and exchanges"},
        {"POST", "/api/v1/money/transfers", "Money: add a transfer or exchange"},
        {"GET", "/api/v1/money/transfers/{id}", "Money: one transfer"},
        {"PATCH", "/api/v1/money/transfers/{id}", "Money: change a transfer's amounts"},
        {"DELETE", "/api/v1/money/transfers/{id}", "Money: delete a transfer"},
        {"GET", "/api/v1/money/merchants", "Money: merchant suggestions with the remembered category"},
        {"PATCH", "/api/v1/money/merchants/{key}", "Money: change what a merchant means from now on"},
        {"GET", "/api/v1/money/rates", "Money: a quote against USD on or before a day"},
        {"GET", "/api/v1/money/rates/convert", "Money: an informational conversion with the rate and its date"},
        {"POST", "/api/v1/money/rates/refresh", "Money: enqueue today's rates fetch, or a backfill of a range"},
        {"POST", "/api/v1/money/import/notion", "Money: load the export of the Notion money databases"},
        {"GET", "/api/v1/money/reports/period", "Money: a period's numbers per currency"},
        {"GET", "/api/v1/money/reports/balances", "Money: accounts and balances grouped by currency"},
        {"POST", "/api/v1/money/parse", "Money: send a bank mail or a list to the LLM parse job"},
        {"POST", "/api/v1/money/parse/receipt", "Money: send a receipt photo to the LLM parse job"},
        {"GET", "/api/v1/money/parse/{id}", "Money: a parse job and its lines"},
        {"POST", "/api/v1/money/parse/{id}/accept", "Money: the edited lines of a parse into the inbox"},
        {"GET", "/api/v1/money/advisor/reports", "Money: the advisor's reviews, newest first"},
        {"GET", "/api/v1/money/advisor/reports/{id}", "Money: one review with the facts it was built on"},
        {"POST", "/api/v1/money/advisor/run", "Money: ask the advisor for a review of a period"},
        {"GET", "/api/v1/money/settings", "Money: the view currency and the advisor settings"},
        {"PUT", "/api/v1/money/settings", "Money: replace the settings"},
        {"GET", "/api/v1/billing/packages", "List active top-up packages"},
        {"GET", "/api/v1/billing/wallet", "Get your own wallet balance + ledger history"},
        {"POST", "/api/v1/billing/topup", "Start a PayPal top-up (package or custom amount)"},
        {"POST", "/api/v1/billing/capture", "Capture an approved PayPal order and credit your wallet"},
        {"POST", "/api/v1/billing/paypal/webhook", "PayPal webhook: verified capture/refund events (public)"},
        {"GET", "/api/v1/admin/billing/payments", "Admin: list payments (paged, filter by status/user)"},
        {"GET", "/api/v1/admin/billing/packages", "Admin: list every top-up package (active and inactive)"},
        {"POST", "/api/v1/admin/billing/packages", "Admin: create a top-up package"},
        {"PATCH", "/api/v1/admin/billing/packages/{id}", "Admin: update a top-up package"},
        {"DELETE", "/api/v1/admin/billing/packages/{id}", "Admin: delete a top-up package"},
        {"GET", "/api/v1/admin/billing/settings", "Admin: read the billing rate/bounds settings"},
        {"PUT", "/api/v1/admin/billing/settings", "Admin: update the billing rate/bounds settings"},
        {"POST", "/api/v1/admin/billing/users/{id}/adjust", "Admin: manually adjust a user's wallet balance"},
        {"GET", "/api/v1/admin/billing/metrics", "Admin: billing metrics (revenue, conversion, refunds)"},
    };
    return endpoints;
}

}  // namespace Api
