/**
 * @file PostsController.hpp
 * @brief Post CRUD endpoints. Generated by scripts/new-resource.sh.
 *        Admin-gated; follows docs/CONVENTIONS.md. Every handler is gated
 *        by Core::content_enabled() — the whole content module is off by
 *        default (CONTENT_ENABLED=false), so a deploy that hasn't run the
 *        posts migration yet returns 404 instead of a 500 against a missing
 *        table.
 *
 * Declarations only — the handler bodies live in PostsController.cpp
 * (compiled once into app_core; ADR 0003 as amended 2026-08-22). The route
 * macros (ADD_METHOD_TO) must stay in this header: Drogon's METHOD_LIST
 * registration is part of the class definition, and
 * scripts/check-routes-registered.sh greps the src/api headers for them.
 */

#pragma once

#include <chrono>
#include <functional>
#include <optional>
#include <string>
#include <vector>

#include <drogon/HttpController.h>

#include <nlohmann/json_fwd.hpp>

#include "api/Validation.hpp"
#include "domain/Post.hpp"
#include "repositories/PostRepository.hpp"

namespace Api {

using namespace drogon;
using json = nlohmann::json;

class PostsController : public HttpController<PostsController> {
public:
    METHOD_LIST_BEGIN
    // Admin CMS (ADMINISTER-gated): full CRUD over every post, drafts included.
    ADD_METHOD_TO(PostsController::listPosts, "/api/v1/posts", Get);
    ADD_METHOD_TO(PostsController::createPost, "/api/v1/posts", Post);
    ADD_METHOD_TO(PostsController::getPost, "/api/v1/posts/{1}", Get);
    ADD_METHOD_TO(PostsController::updatePost, "/api/v1/posts/{1}", Patch);
    ADD_METHOD_TO(PostsController::deletePost, "/api/v1/posts/{1}", Delete);
    ADD_METHOD_TO(PostsController::previewToken, "/api/v1/posts/{1}/preview-token", Post);
    // Public site (no auth): published posts only, addressed by slug.
    ADD_METHOD_TO(PostsController::publicListPosts, "/api/v1/public/posts", Get);
    ADD_METHOD_TO(PostsController::publicGetPost, "/api/v1/public/posts/{1}", Get);
    METHOD_LIST_END

    void listPosts(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback);

    void createPost(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback);

    void getPost(const HttpRequestPtr& req,
                 std::function<void(const HttpResponsePtr&)>&& callback,
                 const std::string& id);

    void updatePost(const HttpRequestPtr& req,
                    std::function<void(const HttpResponsePtr&)>&& callback,
                    const std::string& id);

    void deletePost(const HttpRequestPtr& req,
                    std::function<void(const HttpResponsePtr&)>&& callback,
                    const std::string& id);

    // Draft preview: a stateless HMAC token (purpose=preview, sub=post id,
    // 1h TTL). Reusable within its TTL, nothing stored server-side; the link
    // works for anyone holding it — that's the point of "send to my phone".
    static constexpr std::chrono::seconds kPreviewTtl{3600};

    void previewToken(const HttpRequestPtr& req,
                      std::function<void(const HttpResponsePtr&)>&& callback,
                      const std::string& id);

    // Returns the post for slug honoring an optional ?preview= token:
    // published posts always; a draft only when the token verifies AND is
    // bound to this post. Shared with ContentPagesController::post_markdown.
    static std::optional<Domain::Post> resolve_post(const std::string& slug, const std::string& preview);

    // ── Public site (unauthenticated) ─────────────────────────────────────
    void publicListPosts(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback);

    void publicGetPost(const HttpRequestPtr& req,
                       std::function<void(const HttpResponsePtr&)>&& callback,
                       const std::string& slug);

private:
    // Validate the "tags" field (optional array of non-empty keyword strings,
    // stored comma-joined so commas/line-breaks are rejected). Only call when
    // the body carries "tags"; adds to @p errs on any problem.
    static std::vector<std::string> validate_tags(const json& body, Validation::Errors& errs);

    // Validate every field PRESENT in the body (type, length, enum, slug
    // format). Shared by create (POST) and the partial update (PATCH); neither
    // requires a field here — presence is the caller's concern.
    static void validate_present_fields(const json& body, Validation::Errors& errs);

    // POST create: slug + title required, omitted optionals take defaults.
    static bool read_input(const json& body,
                           Repositories::PostInput& in,
                           const std::function<void(const HttpResponsePtr&)>& callback);

    // PATCH update: seed @p in from the EXISTING post, then overlay ONLY the
    // fields present in the body. An omitted field keeps its current value —
    // crucially, omitting "status" no longer unpublishes the post and drops
    // its published_at (PostRepository::update derives published_at from the
    // status it's handed). Absent-key vs explicit-null are both "keep".
    static bool merge_input(const json& body,
                            const Domain::Post& existing,
                            Repositories::PostInput& in,
                            const std::function<void(const HttpResponsePtr&)>& callback);
};

}  // namespace Api
