#!/usr/bin/env python3
"""Generate the exercise-library seed migration from yuhonas/free-exercise-db.

The dataset is in the public domain (Unlicense). The migration this script
writes is committed; an applied migration is never edited, so a newer dataset
commit goes into a NEW migration number.

Usage:
    scripts/gen-exercise-seed.py <commit-sha> <migration-number> [--json FILE]

Example:
    scripts/gen-exercise-seed.py f00c92c7dcf1216a928a52c3706c7ce8e2f71ed5 018

Without --json the script downloads dist/exercises.json of that commit.
"""

import argparse
import json
import pathlib
import sys
import urllib.request

REPO = "yuhonas/free-exercise-db"


def tracking_mode(ex: dict) -> str:
    """What a set of this exercise records; the owner can change it later."""
    category = ex.get("category") or ""
    if category == "cardio":
        return "distance_duration"
    if category == "stretching":
        return "duration"
    if ex.get("equipment") == "body only" and category in ("strength", "plyometrics"):
        return "bodyweight_reps"
    return "weight_reps"


def lit(value) -> str:
    """SQL literal for a text value or NULL."""
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def arr(values) -> str:
    """SQL literal for a text[] value."""
    if not values:
        return "'{}'"
    return "ARRAY[" + ", ".join(lit(v) for v in values) + "]"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("sha")
    ap.add_argument("number")
    ap.add_argument("--json", dest="json_path")
    args = ap.parse_args()

    if args.json_path:
        raw = pathlib.Path(args.json_path).read_bytes()
    else:
        url = f"https://raw.githubusercontent.com/{REPO}/{args.sha}/dist/exercises.json"
        with urllib.request.urlopen(url) as resp:  # noqa: S310 (fixed https host)
            raw = resp.read()
    exercises = sorted(json.loads(raw), key=lambda e: e["id"])

    out = [
        f"-- Migration {args.number}: workout_exercise_seed — the exercise library.",
        "--",
        "-- GENERATED by scripts/gen-exercise-seed.py. Do not edit by hand, and never",
        "-- edit after it has been applied: a newer dataset goes into a new migration.",
        "--",
        f"-- Source: https://github.com/{REPO} at commit",
        f"-- {args.sha} (public domain, Unlicense).",
        f"-- {len(exercises)} exercises. Image paths are relative to the dataset's",
        "-- exercises/ directory; the frontend image serves them under /exercise-media/.",
        "--",
        "-- Applied in numeric order on boot. The MigrationRunner wraps this file in ONE",
        "-- transaction under an advisory lock — do NOT add BEGIN/COMMIT. Idempotent:",
        "-- a row that already exists is left as it is.",
        "",
    ]
    cols = (
        "id, source, name, category, equipment, level, force, mechanic, "
        "primary_muscles, secondary_muscles, instructions, images, tracking_mode"
    )
    for ex in exercises:
        values = ", ".join(
            [
                lit(ex["id"]),
                "'library'",
                lit(ex["name"]),
                lit(ex.get("category") or "strength"),
                lit(ex.get("equipment")),
                lit(ex.get("level")),
                lit(ex.get("force")),
                lit(ex.get("mechanic")),
                arr(ex.get("primaryMuscles")),
                arr(ex.get("secondaryMuscles")),
                arr(ex.get("instructions")),
                arr(ex.get("images")),
                lit(tracking_mode(ex)),
            ]
        )
        out.append(f"INSERT INTO exercises ({cols}) VALUES ({values}) ON CONFLICT (id) DO NOTHING;")

    root = pathlib.Path(__file__).resolve().parent.parent
    path = root / "migrations" / f"{args.number}_workout_exercise_seed.sql"
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(root)}: {len(exercises)} exercises")
    return 0


if __name__ == "__main__":
    sys.exit(main())
